on:
  push:
    branches:
      - main
  pull_request: {}

name: CI

jobs:
  code-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16 # LTS
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Check Code Lint
        run: npm run-script lint
