on:
  push:
    branches:
      - main
  pull_request: {}

name: CI

jobs:
  code-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            registry.npmjs.org:443
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 18 # LTS
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Check Code Lint
        run: npm run-script lint

