on:
  push:
    branches:
      - main
  pull_request: {}

name: CI

jobs:
  code-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            registry.npmjs.org:443
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: 18 # LTS
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Check Code Lint
        run: npm run-script lint

