on:
  push:
    branches:
      - main
  pull_request: {}

name: CI

jobs:
  code-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            registry.npmjs.org:443
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: 18 # LTS
      - name: Install Dependencies
        run: npm ci --ignore-scripts
      - name: Check Code Lint
        run: npm run-script lint

